import type { ChoiceOption } from "@classtools/domain";
import { newStableId } from "../ids";

interface Props { options: ChoiceOption[]; multiple: boolean; correctOptionId?: string; correctOptionIds?: string[]; onChange: (options: ChoiceOption[], correct: string | string[]) => void }
export function ChoiceEditor({ options, multiple, correctOptionId, correctOptionIds = [], onChange }: Props) {
  const setOption = (id: string, text: string) => onChange(options.map((option) => option.id === id ? { ...option, text } : option), multiple ? correctOptionIds : (correctOptionId ?? ""));
  const setCorrect = (id: string) => onChange(options, multiple ? (correctOptionIds.includes(id) ? correctOptionIds.filter((value) => value !== id) : [...correctOptionIds, id]) : id);
  const remove = (id: string) => { const next = options.filter((option) => option.id !== id); const correct = multiple ? correctOptionIds.filter((value) => value !== id) : (correctOptionId === id ? "" : correctOptionId ?? ""); onChange(next, correct); };
  return <div className="option-editor"><div className="editor-subheading"><span>選項</span><small>文字變更時會保留穩定識別碼。</small></div>{options.map((option, index) => <div className="option-row" key={option.id}><input aria-label={`選項 ${index + 1} 內容`} value={option.text} onChange={(event) => setOption(option.id, event.target.value)} placeholder={`選項 ${index + 1}`} /><label className="correct-control"><input aria-label={`將選項 ${index + 1} 設為正確`} checked={multiple ? correctOptionIds.includes(option.id) : correctOptionId === option.id} onChange={() => setCorrect(option.id)} type={multiple ? "checkbox" : "radio"} name={multiple ? undefined : "correct-option"} /> 正確</label><button aria-label={`刪除選項 ${index + 1}`} className="icon-button danger-icon" disabled={options.length <= 2} onClick={() => remove(option.id)} type="button">×</button></div>)}<button className="button ghost" onClick={() => onChange([...options, { id: newStableId("option"), text: "" }], multiple ? correctOptionIds : correctOptionId ?? "")} type="button">＋ 新增選項</button></div>;
}
