import type { Question, QuestionAsset } from "@classtools/domain";
import { questionToPublicView } from "./helpers";

export function QuestionPreview({ question, assets = [] }: { question: Question; assets?: QuestionAsset[] }) {
  const preview = questionToPublicView(question, assets);
  return <section className="preview-card" aria-label="教師預覽"><div className="preview-header"><span className="eyebrow">學生端預覽</span><span>{question.points} 分</span></div><h3>{preview.prompt || "未命名題目"}</h3>{preview.type === "true_false" && <div className="preview-options"><span>正確</span><span>錯誤</span></div>}{(preview.type === "single_choice" || preview.type === "multiple_choice") && <div className="preview-options">{preview.options?.map((option) => <span key={option.id}>{option.text || "未命名選項"}</span>)}</div>}{preview.type === "fill_blank" && <p className="preview-placeholder">請填寫 {preview.blankCount} 個空格。</p>}{preview.type === "essay" && <div className="preview-essay">學生作答區</div>}{preview.assets.length > 0 && <div className="preview-assets" aria-label="公開附件">{preview.assets.map((asset) => <span key={asset.id}>{asset.assetType === "pdf" ? "PDF" : "圖片"}：{asset.displayName}{asset.pageReference ? ` · 第 ${asset.pageReference} 頁` : ""}</span>)}</div>}<small className="preview-safe-note">預覽不包含正確答案、評分設定、檔案路徑或 checksum。</small></section>;
}

export function AnswerSummary({ question }: { question: Question }) {
  return <section className="answer-summary" aria-label="正確答案摘要"><div className="preview-header"><span className="eyebrow">教師答案摘要</span></div>{question.type === "true_false" && <p>正確答案：<strong>{question.answerConfig.correctAnswer ? "正確" : "錯誤"}</strong></p>}{question.type === "single_choice" && <p>正確選項：<strong>{question.answerConfig.options.find((option) => option.id === question.answerConfig.correctOptionId)?.text || "尚未選擇"}</strong></p>}{question.type === "multiple_choice" && <p>正確選項：<strong>{question.answerConfig.options.filter((option) => question.answerConfig.correctOptionIds.includes(option.id)).map((option) => option.text || "未命名選項").join("、") || "尚未選擇"}</strong></p>}{question.type === "fill_blank" && <ul>{question.answerConfig.blanks.map((blank, index) => <li key={blank.id}>空格 {index + 1}：<strong>{blank.acceptedAnswers.filter(Boolean).join("／") || "尚未設定可接受答案"}</strong></li>)}</ul>}{question.type === "essay" && <p>申論題的評分狀態為<strong>待評閱</strong>。</p>}</section>;
}
